### PR TITLE
Homebrew changes

### PR DESCRIPTION
**Pull request by rockbruno**
@Dschee here it is! Basically, this PR:
- Changes homebrew to install from the release zip instead of compiling the sources, so we can ship it together with CocoaPods
- Changes how the tool searches for the libraries so we can make homebrew place them in the correct places (bin/include)
- Changes the makefile to do all the folder processing after building (there's some files that the final .zip doesn't need and I used to remove them manually...)
- Updates tests

I also removed the recommended tag from homebrew because the version of this tool is important for SwiftInfo-Reader, so I assume team projects will mostly use CocoaPods.

Let me know what you think and I'll push a new 2.2.1 tag so this can be tested remotely.

### CODE REVIEW

**Comment by Dschee** [comment]
As long as this change still let's me install SwiftInfo without a Podfile and instead just by running `brew install swiftinfo`, then I'm totally fine with the changes. It even saves build time. 🎉 

Please note though, that I don't understand how `system "false"` is testing out that swifinfo was correctly installed. I'd rather do something like `system "swifinfo version"` and check if that works (like I do [here](https://github.com/JamitLabs/Accio/blob/stable/Formula/accio.rb#L14)).

**Comment by rockbruno** [comment]
I was super lazy 😆 Will do it

**Comment by rockbruno** [comment]
Done.

**Comment by rockbruno** [comment]
I only got it to work using `brew install rockbruno/SwiftInfo/swiftinfo`... If I used `brew install swiftinfo`, it tries to download one of the test versions that I pushed even if I clean all caches... No idea where that's coming from. Updated the README for now, will check that out later

**Comment by rockbruno** [comment]
Thanks again @Dschee !

**Pull request merged**
